1648645966545	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1648645966874	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1648646566545	Sync.Service	DEBUG	User-Agent: Firefox/98.0.2 (Linux x86_64) FxSync/1.100.0.20220323001514.desktop
1648646566546	Sync.Service	INFO	Starting sync at 2022-03-30 18:52:46 in browser session 58R8m8Sl_Qed
1648646566546	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648646566548	Sync.Status	INFO	Resetting Status.
1648646566548	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1648646566549	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1648646566549	FirefoxAccounts	DEBUG	getOAuthToken enter
1648646566549	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648646566549	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648646566550	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1648646566650	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2153390067 - 
1648646566651	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"<no message>\"  nsresult: \"0x805a1ff3 (<unknown>)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1648646566661	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1648646566661	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1648646566661	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1648646566663	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
